#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan  5 15:45:58 2019

@author: omerorhan
"""


import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


#import the mall dataset
dataset = pd.read_csv("Mall_Customers.csv")
x = dataset.iloc[:,[3,4]].values

#using the dendrogram to find the optimal number of clusters
import scipy.cluster.hierarchy as sch
dendrogram = sch.dendrogram(sch.linkage(x,method= 'ward'))
plt.title('Dendrogram method')
plt.xlabel('customers')
plt.ylabel('euclidean distances')
plt.show()

#fitting hierarchical clustering to the mall dataset 
from sklearn.cluster import AgglomerativeClustering 
hc = AgglomerativeClustering(n_clusters= 5, affinity='euclidean',linkage='ward')
y_hc =  hc.fit_predict(x)

#visualising the clusters
plt.scatter(x[y_hc == 0,0], x[y_hc == 0,1], s=100, c='red',label= 'careful') 
plt.scatter(x[y_hc == 1,0], x[y_hc == 1,1], s=100, c='blue',label= 'standart')
plt.scatter(x[y_hc == 2,0], x[y_hc == 2,1], s=100, c='green',label= 'target')
plt.scatter(x[y_hc == 3,0], x[y_hc == 3,1], s=100, c='cyan',label= 'careless')
plt.scatter(x[y_hc == 4,0], x[y_hc == 4,1], s=100, c='magenta',label= 'sensible') 
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=300,c='yellow', label='centroids')
plt.title('cluster of customers')
plt.xlabel('annual income $')
plt.ylabel('spending score(1-100)')
plt.legend()
plt.show()